name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run tests with Gradle
      run: ./gradlew test
